# Generated by Django 3.2.5 on 2021-10-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_auto_20211010_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(null=True, upload_to='Audios'),
        ),
    ]
