# Generated by Django 3.2.5 on 2021-10-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_alter_song_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favsongs',
            name='is_favorite',
        ),
    ]
