# Generated by Django 3.2.5 on 2021-11-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_remove_favsongs_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(null=True, upload_to='AlbumCover/'),
        ),
    ]
